In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [3]:
torch.manual_seed(1)

In [4]:
## simple one-variable Linear Regression

x_train = torch.FloatTensor([1.0, 2.0, 3.0])
y_train = torch.FloatTensor([3.5, 6.5, 9.5])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

epoch = 1999
for ep in range(epoch+2) :
  
  hyp = x_train*W+b
  cost = torch.mean( (hyp-y_train)**2 )

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if ep%500==0 :
     print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            ep, epoch, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.300, b: 0.130 Cost: 48.250000
Epoch  500/1999 W: 2.910, b: 0.706 Cost: 0.006097
Epoch 1000/1999 W: 2.973, b: 0.562 Cost: 0.000549
Epoch 1500/1999 W: 2.992, b: 0.519 Cost: 0.000049
Epoch 2000/1999 W: 2.998, b: 0.506 Cost: 0.000004


In [5]:
## 기울기 구하기

z = torch.tensor(1.0, requires_grad = True)

x = z**z+z**5+3*z+3
y = x**(3)

y.backward()
print('수식을 w로 미분한 값 : {}'.format(z.grad))


수식을 w로 미분한 값 : 1728.0


In [6]:
## simple multi-variable Linear Regression

x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 7999
for epoch in range(nb_epochs+2) :

  hyp = w1*x1_train+w2*x2_train+w3*x3_train+b
  cost = torch.mean( (hyp-y_train)**2 )

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%2000==0 :
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))



Epoch    0/7999 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch 2000/7999 w1: 0.757 w2: 0.571 w3: 0.682 b: 0.011 Cost: 0.754379
Epoch 4000/7999 w1: 0.812 w2: 0.517 w3: 0.681 b: 0.013 Cost: 0.448557
Epoch 6000/7999 w1: 0.848 w2: 0.488 w3: 0.675 b: 0.015 Cost: 0.337360
Epoch 8000/7999 w1: 0.871 w2: 0.472 w3: 0.667 b: 0.018 Cost: 0.292709


In [7]:
## simple multi-variable Linear Regression (Matrix ver.)

x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 10000
for epoch in range(nb_epochs+2) :

  hyp = x_train.matmul(W)+b
  cost = torch.mean( (y_train-hyp)**2 )

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%1000==0 :
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, hyp.squeeze().detach(), cost.item()))

  

Epoch    0/10000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch 1000/10000 hypothesis: tensor([153.8955, 184.8841, 176.6536, 198.0995, 141.2951]) Cost: 3.941853
Epoch 2000/10000 hypothesis: tensor([153.7204, 184.7364, 177.3512, 197.6782, 141.4043]) Cost: 2.643340
Epoch 3000/10000 hypothesis: tensor([153.5477, 184.6475, 177.8806, 197.3408, 141.5250]) Cost: 1.806990
Epoch 4000/10000 hypothesis: tensor([153.3855, 184.5969, 178.2860, 197.0692, 141.6459]) Cost: 1.257653
Epoch 5000/10000 hypothesis: tensor([153.2379, 184.5707, 178.5994, 196.8493, 141.7604]) Cost: 0.891409
Epoch 6000/10000 hypothesis: tensor([153.1065, 184.5599, 178.8437, 196.6707, 141.8653]) Cost: 0.644614
Epoch 7000/10000 hypothesis: tensor([152.9913, 184.5584, 179.0356, 196.5250, 141.9590]) Cost: 0.477002
Epoch 8000/10000 hypothesis: tensor([152.8914, 184.5623, 179.1876, 196.4059, 142.0414]) Cost: 0.362521
Epoch 9000/10000 hypothesis: tensor([152.8055, 184.5690, 179.3087, 196.3082, 142.1130]) Cost: 0.284

In [10]:
## simple one-variable Linear Regression (torch.nn ver.) 

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = torch.nn.Linear(1, 1)     # nn.Linear(input_dim, output_dim))
print(list(model.parameters()))   # randomly initialized

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs) :

  prediction = model(x_train)
  cost = torch.mean((prediction-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 400 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

  
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)

[Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]
Epoch    0/2000 Cost: 33.679783
Epoch  400/2000 Cost: 0.052656
Epoch  800/2000 Cost: 0.007678
Epoch 1200/2000 Cost: 0.001119
Epoch 1600/2000 Cost: 0.000163
tensor([[7.9902]], grad_fn=<AddmmBackward>)


## 클래스로 Linear Regression 구현하기

In [20]:
# One-variable Linear Regression

class LinearRegressionModel(torch.nn.Module) :
  def __init__(self) :
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x) :
    return self.linear(x)

model_one = LinearRegressionModel()

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

optimizer = torch.optim.SGD(model_one.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs) :

  pred_x = model(x_train)
  cost = F.mse_loss(pred_x, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 500 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))


Epoch    0/2000 Cost: 18.474602
Epoch  500/2000 Cost: 18.474602
Epoch 1000/2000 Cost: 18.474602
Epoch 1500/2000 Cost: 18.474602


In [19]:
# Multi-variable Linear Regression

class MultiVariableLinearRegressionModel(torch.nn.Module) :
  def __init__(self) :
    super().__init__()
    self.linear = nn.Linear(3,1)
  
  def forward(self, W) :
    return self.linear(W)
  
model_multi = MultiVariableLinearRegressionModel()

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

optimizer = torch.optim.SGD(model_multi.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs) :

  pred_x = model_multi(x_train)
  cost = F.mse_loss(pred_x, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 500 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))


Epoch    0/2000 Cost: 17620.488281
Epoch  500/2000 Cost: 0.498932
Epoch 1000/2000 Cost: 0.424674
Epoch 1500/2000 Cost: 0.367987
